// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RPGHelper.Context.InfoTables.WarhammerFantasy;

#nullable disable

namespace RPGHelper.Context.Migrations
{
    [DbContext(typeof(WarhammerContext))]
    [Migration("20220123163412_AddedFirstIteration")]
    partial class AddedFirstIteration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");
#pragma warning restore 612, 618
        }
    }
}
